---
apiVersion: v1
kind: Pod
metadata: 
  name: web
  labels:
    name: web
    end: frentend
spec:
  containers:
  - image: rajumirthipati/web:v1
    name: web
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    command: ["sleep","50000"]
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  ports:
  - protocal: TCP
    port: 80
    targetPort: 80
  selector:
    name: web
    end: frentend
 
      