---
apiVersion: v1
kind: Pod
metadata: 
  name: web
  labels:
    name: web
    end: frentend
spec:
  containers:
  - image: rajumirthipati/web:k8
    name: web
    imagePullPolicy: Always
    Ports:
    - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    name: web
    end: frentend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
      