---
apiVersion: v1
kind: Pod
metadata: 
  name: new-web
  labels:
    name: web
    end: frontend
spec:
  containers:
  - image: rajumirthipati/web:v1
    name: new-web
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    command: ["sleep","50000"]
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    name: web
    end: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
