apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
  - name: tcp
    port: 27017
    targetPort: 27017
  
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  containers:
  - name: mongodb
    image: rajumirthipati/mongo:v1
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"  
      limits:
        cpu: "100m"
        memory: "500Mi"
    ports:
        - containerPort: 27017

