apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_DATABASE: "cities"
  MYSQL_ROOT_PASSWORD: "raju"
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: rajumirthipati/mysql:v1
    envFrom:
    - configMapRef:
        name: mysql-config
    - secretRef:
        name: mysql-secret
    command: ["mysqld"]
    args: ["--bind-address=0.0.0.0", "--user=mysql"]
    ports:
      - containerPort: 3306
---