---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  data:
    MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    app: catalogue
    tier: middile
spec:
  containers:
  - name: catalogue
    image: rajumirthipati/catalogue:v1
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "100Mi"  
      limits:
        cpu: "100m"
        memory: "500Mi"
    envFrom:
      - configMapRef:
        name: catalogue-config     
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    app: catalogue
    tier: middile
  ports:
  - name: tcp
    port: 80
    targetPort: 8080
