---
apiVersion: v1
kind: Pod
metadata: 
  name: redis
  labels:
    tier: middile 
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 6379
---
apiVersion: v1    
kind: Service
metadata:
  name: redis
spec:
  selector:
    tier: middile 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
  

